### ISSUE TITLE
Create specs

### ISSUE THREAD

**Issue by weslleyaraujo** [r7com/r7-component#1]

**Comment by dpsxp** [comment]
Mocha and Chai?
http://mochajs.org/
http://chaijs.com/

**Comment by weslleyaraujo** [comment]
Começei uma branch com jasmine, mas se quizer mocha pode mandar bala!!

To fazendo um grunt legal pra gerar versao rodar testes e os carai.. Da pra
mudar sussa de mocha pra jasmine

On Monday, February 2, 2015, Daniel Paulino notifications@github.com
wrote:

> Mocha?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/r7com/r7-component/issues/1#issuecomment-72501116.

## 

_Weslley Araujo_

_Web Developer_
_+55 (11) 96539-6299_
_weslleydeveloper.com http://weslleydeveloper.com_

**Comment by guilhermehn** [comment]
+1 pra mocha e chai

**Comment by tcelestino** [comment]
+1 para jasmine!

**Comment by guilhermepontes** [comment]
+1 pra qunit

**Comment by guilhermehn** [comment]
@guilhermepontes let the treta begins

**Comment by guilhermepontes** [comment]
:trollface:

**Comment by weslleyaraujo** [comment]
Galera a favor de outros frameworks diferente de jasmine, favor criar uma branch utilizando o framework desejado e enviar pull request pra fazermos a decisão.

**Comment by guilhermepontes** [comment]
> @weslleyaraujo  Galera a favor de outros frameworks diferente de jasmine, favor criar uma branch utilizando o framework desejado e enviar pull request pra fazermos a decisão.

Posso usar o `weslleyaraujo/testsuite`? :grin:

**Comment by weslleyaraujo** [comment]
hahahahhahahahah esse vai dar ruim com certeza @guilhermepontes  :cry:

**Comment by rodrigomilfont** [comment]
O sr está um fanfarrão, hein @guilhermepontes! :D

2015-02-05 20:00 GMT-02:00 Weslley Araujo notifications@github.com:

**Comment by guilhermepontes** [comment]
:trollface:

**Comment by dpsxp** [comment]
closed by #7

**Comment by rodrigomilfont** [comment]
Rodrigo Milfont loves MUBI and thinks you might love it too.

At MUBI we think life is too short for bad films.
So, every day we add a cinematic gem to our carefully curated selection and you have 30 days to watch.

Start Your Free Month: https://mubi.com/tell-a-friend/email/1inut4k?utm_campaign=invitation&utm_source=refer_friend&utm_medium=email
