### ISSUE TITLE
R7.helpers

### ISSUE THREAD

**Issue by guilhermehn** [r7com/r7-component#6]
Na linha onde é definido o objeto de helpers:
https://github.com/r7com/r7-component/blob/master/src/core/r7-component.js#L37

Existe um motivo para este objeto ser definido assim, que considera a pré-definição?

**Comment by weslleyaraujo** [comment]
Na real existe, só foi feito isso porque como vamos utilizar ele dentro do schumi, la dentro ja temos um projeto (footstats) usando a global `R7` e adicionando a chave `R7.helpers` tambem..

Quando fecharmos uma versão do r7-component podemos ajustar essa linha :)
